alias tardis='ssh ssh.tardis.ed.ac.uk -l shearn89'
alias dice='ssh ssh.inf.ed.ac.uk -l s0700157'
alias ls='ls --color=auto'
alias dice-ftp='sftp s0700157@ssh.inf.ed.ac.uk'
alias diceX='ssh ssh.inf.ed.ac.uk -l s0700157 -X'
alias hist='history | grep $1'
alias systemC='sshfs s0700157@ssh.inf.ed.ac.uk:/home/sviglas/courses/inf2c/systemC/ /home/sviglas/courses/inf2c/systemC/'
alias nltk='export NLTK_DATA=/home/shearn89/nltk_data'
alias pl='prolog'
