alias ls='ls --color=auto'
alias ll='ls -l'

alias gst='git status '
alias gc='git commit '
alias gl='git pull '
alias gp='git push '
alias ga='git add '
alias gfa='git fetch --all '

if [[ -f /usr/bin/nvim ]]
then
  alias vim='nvim -p '
else 
  alias vim='vim -p '
fi

alias sizes='du -sh * | sort --human-numeric'

alias bert='bundle exec rake test '
alias bip='bundle install --path=vendor/bundle '

alias feh='feh --auto-rotate -P '
alias show_photos='feh -. --auto-rotate -F -B black -P -Y ./'

function findextgrep () {
  if [[ -z $1 ]]
  then
    echo 'must provide search path'
    return 1
  fi

  if [[ -z $2 ]]
  then
    echo 'must provide extension'
    return 1
  fi

  if [[ -z $3 ]]
  then
    echo 'must provide search string'
    return 1
  fi

  find $1 -iname "${2}" -exec grep -H -i $3 {} \;
}

gr () {
  directory=$(git rev-parse --show-cdup --no-revs HEAD)
  if [ -z $directory ]
  then
    directory=$(basename $(pwd))
  else
    cd $directory
  fi
  name=$(basename $directory)
  describe=$(git describe --tags 2>/dev/null || git rev-parse --short HEAD)
  git archive --prefix=$name/ -o $name-$describe.tar.gz HEAD ./
}

cdt (){
  directory=$(git rev-parse --show-cdup --no-revs HEAD)
  if [ ! -z $directory ]
  then
    cd $directory
  fi
}

burndisk () {
  sudo wodim -eject -tao speed=2 dev=/dev/sr0 -v -data $1
}
