zmodload zsh/zprof
# export ZSH="$HOME/.oh-my-zsh"
# source $ZSH/oh-my-zsh.sh

autoload -Uz compinit
compinit -C

source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
# antidote load ${ZDOTDIR:-$HOME}/.zsh_plugins.txt
# Update with:   antidote bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.zsh
source ~/.zsh_plugins.zsh

# # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# # Initialization code that may require console input (password prompts, [y/n]
# # confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="underline"

# THEME STUFF
POREWLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_COLOR_SCHEME="$(dark-notify -e)"
POWERLEVEL9K_VI_INSERT_MODE_STRING="\uf80b"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="\uf80f"
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0b4'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$'\uE0b5'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0b6'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$'\uE0b7'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='red'
# POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform'
# POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi'
# shorten long directory lists
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
# transient prompt in same directory, saves space
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
# set up multi-line prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode context dir dir_writable vcs aws virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ssh root_indicator background_jobs kubecontext history time battery)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# MAGIC_ENTER_OTHER_COMMAND=''
export ZSH_DOTENV_ALLOWED_LIST=$HOME/.cache/dotenv/allowed/list
export ZSH_DOTENV_DISALLOWED_LIST=$HOME/.cache/dotenv/disallowed/list
export ZSH_DOTENV_PROMPT=true
export DOTENV_ALLOWED_LIST=$HOME/.cache/dotenv/allowed/list
export DOTENV_DISALLOWED_LIST=$HOME/.cache/dotenv/disallowed/list

# HISTORY STUFF
HISTFILE="$HOME/.zhistory"
HISTSIZE=10000
HISTFILESIZE=5000
HISTORY_IGNORE="(l[alsh]#( *)#|[bf]g *|exit|pwd|clear)"
HISTIGNORE="(l[alsh]#( *)#|[bf]g *|exit|pwd|clear)"
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt NO_NOMATCH

# Misc options
export KEYTIMEOUT=1
export EDITOR=nvim
export PAGER='less -FRX'

eval "$(pyenv init -)"

## Auto complete aws cli
# autoload -Uz compinit
# compinit
# autoload bashcompinit && bashcompinit
# complete -C /opt/homebrew/bin/aws_completer aws

# export GPG_TTY=$(tty)
# export NVM_DIR=~/.nvm
# source $(brew --prefix nvm)/nvm.sh

export PATH=$PATH:~/.toolbox/bin:~/go/bin:~/.local/bin
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export PATH="/opt/homebrew/opt/uutils-coreutils/libexec/uubin:$PATH"


bindkey -v

source ~/.bash_aliases
source ~/.config/op/plugins.sh
source /opt/homebrew/opt/autoenv/activate.sh

eval "$(op completion zsh)"
eval "$(thefuck --alias)"
eval "$(gh copilot alias -- zsh)"

# glob/alias expansion
# export ZPWR_EXPAND=true
# export ZPWR_EXPAND_SECOND_POSITION=true
# export ZPWR_EXPAND_NATIVE=false
# export ZPWR_EXPAND_TO_HISTORY=true
export YSU_HARDCORE=1

export KRAKEN_CLI_USE_FZF=1
export KRAKEN_CLI_ROLE=platform_team
export OP_MFA_ITEM="AWS - KTL Users - IAM - Me"

export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
export PIP_REQUIRE_VIRTUALENV=true

export HOMEBREW_NO_VERIFY_ATTESTATIONS=1

fpath+=~/.zfunc; autoload -Uz compinit; compinit

zstyle ':completion:*' menu select

export MISE_PYTHON_UV_VENV_AUTO=true
eval "$(/opt/homebrew/bin/mise activate zsh)"

export PRE_COMMIT_ALLOW_NO_CONFIG=1
