---
  - name: create source directory
    file:
      path: "~/source"
      mode: '0755'
      state: 'directory'

  - name: install essential archlinux base packages
    become: True
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - base-devel
      - xorg
      - git
      - tree
      - jq
      - curl
      - python3
      - python2
      - wget
      - tar
      - xz
      - pigz
      - tmux
      - bash-completion
      - ruby
      - rubygems
      - nodejs-lts-carbon
      - npm
      - xclip
      - xsel
      - python2-neovim
      - python-neovim
      - neovim
      - dmenu
      - compton
      - feh
      - lightdm
      - clamav
      - docker
      - adobe-source-code-pro-fonts

  - name: clone yay from AUR
    git:
      repo: "https://aur.archlinux.org/yay.git"
      dest: "~/source/yay"
      update: yes

  - name: install yay on archlinux
    command: "makepkg -si --noconfirm --noprogressbar"
    args:
      chdir: "~/source/yay"
      creates: "/usr/bin/yay"

  - name: install extra archlinux packages
    command: "yay -Sy --noconfirm {{ item.name }}"
    args:
      creates: "/usr/bin/{{ item.binary }}"
    with_items:
      - name: slstatus-git
        binary: slstatus
      - name: dwm
        binary: dwm
      - name: st-solarized
        binary: st
      - name: vivaldi
        binary: vivaldi-stable
    # - name: code
    #   binary: code
