---
- name: copy files into place
  copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'bashrc', dest: '~/.bashrc' }
    - { src: 'bash_aliases', dest: '~/.bash_aliases' }
    - { src: 'profile', dest: '~/.profile' }
    - { src: 'gemrc', dest: '~/.gemrc' }
    - { src: 'tmux.conf', dest: '~/.tmux.conf' }
    - { src: 'xinitrc', dest: '~/.xinitrc' }
    - { src: 'Xmodmap', dest: '~/.Xmodmap' }
    - { src: 'vscode-extensions', dest: '~/vscode-extensions' }

- name: remove bash_profile
  file:
    path: "~/.bash_profile"
    state: "absent"
