---
- name: install packages
  import_tasks: packages.yml

- name: set up dotfiles
  import_tasks: files.yml

- name: set up vim
  import_tasks: vim.yml

- name: clone repos
  import_tasks: repos.yml

- name: set up rvm
  become: True
  import_role: 
    role: rvm.ruby
  vars:
    rvm1_rubies: ['ruby-2.1.10', 'ruby-2.4.5']
    rvm1_install_flags: ''
    rvm1_install_path: '/usr/local/rvm'
    rvm1_user: 'root'

- name: Set GUI as default
  become: True
  shell: systemctl set-default graphical.target
  
- name: Switch to GUI
  become: True
  shell: systemctl isolate graphical.target
