---
- name: install packages
  import_tasks: packages.yml
  tags:
    - packages

- name: set up dotfiles
  import_tasks: files.yml
  tags:
    - dotfiles

- name: set up vim
  import_tasks: vim.yml
  tags:
    - vim

- name: clone repos
  import_tasks: repos.yml
  tags:
    - gitrepos

- name: include misc stuff
  import_tasks: misc.yml
  tags:
    - misc

- name: include fonts
  when: ansible_distribution != "MacOSX"
  import_tasks: fonts.yml
  tags:
    - fonts

- name: set up rvm
  become: True
  when: ansible_distribution != "MacOSX"
  import_role:
    role: rvm.ruby
  vars:
    rvm1_rubies: ['ruby-2.4.5']
    rvm1_install_flags: ''
    rvm1_install_path: '/usr/local/rvm'
    rvm1_user: 'root'
  tags:
    - rvm
    - never # disable, not using ruby these days

- name: load dconf
  import_tasks: dconf.yml
  when: ansible_distribution != "MacOSX"
  tags:
    - dconf

- name: Enable gui
  import_tasks: gui.yml
  when: ansible_distribution != "MacOSX"
  tags:
    - gui
    - never
