---
- name: get omzsh downloader
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "~/install-omzsh.sh"
    mode: 0755

- name: restore zshrc
  shell: mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
  args:
    removes: ~/.zshrc.pre-oh-my-zsh
