---
- name: install antigen for omzsh
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
    dest: "~/.config/antigen.zsh"
    mode: 0644

- name: install omzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "~/.oh-my-zsh"

- name: restore zshrc
  shell: mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
  args:
    removes: ~/.zshrc.pre-oh-my-zsh
