---
  - import_tasks: tasks/ubuntu/packages.yml
    become: True
    when: ansible_os_family == 'Debian'
    tags:
      - ubuntu

  - import_tasks: tasks/archlinux/packages.yml
    when: ansible_os_family == 'Archlinux'
    tags:
      - arch

  - import_tasks: tasks/fedora/packages.yml
    when: ansible_distribution == 'Fedora'
    tags:
      - fedora
