---
  - name: Install common packages
    package:
      name:
        - adobe-source-code-pro-fonts
        - bash-completion
        - curl
        - dmenu
        - feh
        - firefox
        - git
        - gpg
        - htop
        - jq
        - libselinux-python
        - mlocate
        - mosh
        - neovim
        - pigz
        - python3
        - python3-neovim
        - tar
        - tmux
        - tree
        - wget
        - xz
      state: present
  
  - import_tasks: tasks/ubuntu/packages.yml
    become: True
    when: ansible_os_family == 'Debian'
    tags:
      - ubuntu

  - import_tasks: tasks/archlinux/packages.yml
    when: ansible_os_family == 'Archlinux'
    tags:
      - arch

  - import_tasks: tasks/fedora/packages.yml
    when: ansible_distribution == 'Fedora'
    tags:
      - fedora
