---
  - name: Set sudo flag
    set_fact:
      needs_sudo: "{{ ansible_os_family != 'Darwin' }}"

  - name: Install common packages
    become: "{{ needs_sudo }}"
    package:
      name:
        - autojump
        - bash-completion
        - curl
        - git
        - gpg
        - htop
        - jq
        - mosh
        - neovim
        - pigz
        - tree
        - wget
        - xz
        - zsh
        - rsync
        - pv
        - unzip
      state: present
      
  - name: Install common linux packages
    become: "{{ needs_sudo }}"
    package:
      name:
        - adobe-source-code-pro-fonts
        - firefox
        - libselinux-python
        - mlocate
        - python3-neovim
        - tar
        - crontabs
      state: present
    when: ansible_distribution != 'MacOSX'

  - import_tasks: tasks/ubuntu/packages.yml
    become: True
    when: ansible_os_family == 'Debian'
    tags:
      - ubuntu

  - import_tasks: tasks/archlinux/packages.yml
    when: ansible_os_family == 'Archlinux'
    tags:
      - arch

  - import_tasks: tasks/fedora/packages.yml
    when: ansible_distribution == 'Fedora'
    tags:
      - fedora
  
  - import_tasks: tasks/macos/packages.yml
    when: ansible_distribution == 'MacOSX'
    tags:
      - macos
