---
  - name: Install common packages
    become: True
    package:
      name:
        - autojump
        - bash-completion
        - curl
        - dmenu
        - feh
        - git
        - gpg
        - htop
        - jq
        - mosh
        - neovim
        - pigz
        - python3
        - tmux
        - tree
        - wget
        - xz
        - zsh
        - rsync
        - logrotate
        - pv
        - unzip
        - direnv
        - elvish
      state: present
      
  - name: Install common linux packages
    become: True
    package:
      name:
        - adobe-source-code-pro-fonts
        - firefox
        - libselinux-python
        - mlocate
        - python3-neovim
        - tar
        - crontabs
      state: present

  - import_tasks: tasks/ubuntu/packages.yml
    become: True
    when: ansible_os_family == 'Debian'
    tags:
      - ubuntu

  - import_tasks: tasks/archlinux/packages.yml
    when: ansible_os_family == 'Archlinux'
    tags:
      - arch

  - import_tasks: tasks/fedora/packages.yml
    when: ansible_distribution == 'Fedora'
    tags:
      - fedora
  
  - import_tasks: tasks/macos/packages.yml
    when: ansible_distribution == 'MacOSX'
    tags:
      - macos
