---
- name: create vim plugin folders
  file:
    path: "{{ item }}"
    mode: '0755'
    state: 'directory'
  with_items:
    - "~/.local/share/nvim/site/autoload/"

- name: set symlink for neovim config
  file:
    path: "~/.config/nvim/init.vim"
    dest: "~/.vimrc"
    mode: "0644"
    state: link

- name: download vim-plug
  get_url:
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
