---
  - name: install essential base Fedora packages
    become: True
    dnf:
      state: present
      name:
        - "@base-x"
        - "@gnome"
        - "@virtualization"
        - autojump-zsh
        - cinnamon
        - dnf-plugins-core
        - flatpak
        - gdm 
        - gnome-shell
        - libfm-gtk
        - neovim
        - python2
        - python2-neovim
        - util-linux-user
        - yum-utils
        - net-tools

  - name: Add Docker Fedora Repo
    become: True
    shell: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
    args:
      creates: /etc/yum.repos.d/docker-ce.repo
      warn: False

  - name: Add Puppet 5 Fedora Repo
    become: True
    dnf:
      name: https://yum.puppet.com/puppet5/puppet5-release-fedora-29.noarch.rpm
      state: present

  - name: Add the flathub repo to Flatpak
    become: True
    when: home | bool
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: install non-standard Fedora packages
    become: True
    dnf:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - puppet-agent
      state: present
      update_cache: yes

  - name: Install Flatpaks
    become: True
    when: home | bool
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - com.spotify.Client
      - org.videolan.VLC
      - im.riot.Riot
      - com.discordapp.Discord
      - com.valvesoftware.Steam
    tags:
      - flatpaks
